export const ImagePart = `fragment ImagePart on UploadFileEntityResponse { __typename data { id __typename attributes { __typename name alternativeText caption formats width height mime size url } } }`
export const ImagesPart = `fragment ImagesParts on UploadFileRelationResponseCollection { __typename data { id __typename attributes { __typename name alternativeText caption width formats height mime size url } } }`
export const SeoPart =  `fragment SeoPart on ComponentSharedSeo {   __typename id keywords metaTitle metaDescription }`
export const SeriePart = ` ${SeoPart} fragment SeriePart on SerieEntity { attributes { title type description slug Features { id text image { data { attributes { width url formats height } } } } image { data { attributes { url width height } } } seo { ...SeoPart } } }`
export const SeriePartLocale = ` fragment SeriePartLocale on SerieEntity { attributes { title type description slug Features { id text image { data { attributes { width url height formats } } } } products { data { id ...ProductPart } } image { data { attributes { url width height } } } seo { ...SeoPart } } }`
export const SeriesPartNoSeo = `${SeoPart} fragment SeriePartNoSeo on SerieEntity { id __typename attributes { __typename title type description slug imglogo { ...ImagePart } Features { id description text image { ...ImagePart } } calc_description image { ...ImagePart } } }`
export const ProductPart = `${ImagePart} ${ImagesPart} fragment ProductPart on ProductEntity { attributes { type slug title  place class  product_category { data { __typename id attributes { title slug } } } images {   ...ImagesParts   } series { data { attributes { slug title  Features { description id __typename text link image { ...ImagePart } } } } } description variants { id size thickness quanity_in_box sqrt weight specific_weight kmp adhesion temp } } }`

export const PostPart = `${ImagePart} fragment PostPart on PostEntity { id __typename attributes { title text shortText image { ...ImagePart } slug } }`
export const SectionPart = `${SeriesPartNoSeo} fragment SectionPart on SectionRelationResponseCollection { __typename data { id attributes { __typename nextLink media { data { attributes { name mime url formats } } } title background { __typename data { id __typename attributes { __typename url formats width height } } } type cards { __typename id text link description image { __typename data { __typename id attributes { url width height formats } } } } products { __typename data { __typename id attributes { __typename title    variants { quanity_in_box size sqrt thickness weight } place images { ...ImagesParts } series { __typename data { attributes { title } } } class product_category { __typename data { __typename id attributes { __typename title slug } } } slug } } } Links { __typename id text url } shortText   car_class_calcs { __typename data { __typename attributes { slug title __typename subtitle } id } } series { __typename data { ...SeriePartNoSeo } } } } }`
