export const ImagePart = `fragment ImagePart on UploadFileEntityResponse { __typename data { id __typename attributes { __typename name alternativeText caption width height mime size url } } }`
export const ImagesPart = `fragment ImagesParts on UploadFileRelationResponseCollection { __typename data { id __typename attributes { __typename name alternativeText caption width height mime size url } } }`
export const SeoPart =  `fragment SeoPart on ComponentSharedSeo {   __typename id keywords metaTitle metaDescription }`
export const SeriePart = ` ${SeoPart} fragment SeriePart on SerieEntity { attributes { title type description slug Features { id text image { data { attributes { width url height } } } } image { data { attributes { url width height } } } seo { ...SeoPart } } }`
export const SeriePartLocale = ` fragment SeriePartLocale on SerieEntity { attributes { title type description slug Features { id text image { data { attributes { width url height } } } } products { data { id ...ProductPart } } image { data { attributes { url width height } } } seo { ...SeoPart } } }`
export const SeriesPartNoSeo = `${SeoPart} fragment SeriePartNoSeo on SerieEntity { id __typename attributes { __typename title type description slug imglogo { ...ImagePart } Features { id description text image { ...ImagePart } } calc_description image { ...ImagePart } } }`
export const ProductPart = `fragment ProductPart on ProductEntity { attributes { type slug title  place class  product_category { data { __typename id attributes { title } } } images { data { id attributes { width height url } } } series { data { attributes { slug title } } } description variants { id size thickness quanity_in_box sqrt weight specific_weight kmp adhesion temp } } }`

export const PostPart = `${ImagePart} fragment PostPart on PostEntity { id __typename attributes { title text shortText image { ...ImagePart } slug } }`
export const SectionPart = `${SeriesPartNoSeo} fragment SectionPart on SectionRelationResponseCollection { __typename data { id attributes { __typename nextLink media { data { attributes { name mime url } } } title background { __typename data { id __typename attributes { __typename url width height } } } type cards { __typename id text link description image { __typename data { __typename id attributes { url width height } } } } products { __typename data { __typename id attributes { __typename title images { ...ImagesParts } product_category { __typename data { __typename id attributes { __typename title slug } } } slug } } } Links { __typename id text url } shortText   car_class_calcs { __typename data { __typename attributes { slug title __typename subtitle } id } } series { __typename data { ...SeriePartNoSeo } } } } }`
